version: 2

defaults: &defaults
  docker:
    - image: circleci/android:api-28-alpha
  environment:
    JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Deploy the app to the alpha track
          command: bundle exec fastlane $FASTLANE_LANE
          no_output_timeout: 60m
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
jobs:
  job-deploy-to-alpha:
    environment:
      FASTLANE_LANE: deploy_alpha
    <<: *defaults

  job-deploy-to-beta:
    environment:
      FASTLANE_LANE: deploy_beta
    <<: *defaults

workflows:
  version: 2
  workflow-deploy-builds:
    jobs:
      - job-deploy-to-alpha
      - job-deploy-to-beta:
          requires:
            - job-deploy-to-alpha
